FROM ubuntu:14.04

RUN apt-get update && apt-get install -y make \
    unrar-free autoconf automake libtool gcc g++ gperf \
    flex bison texinfo gawk ncurses-dev libexpat-dev \
    python-dev python python-serial \
    sed git unzip bash help2man wget bzip2
