version: 2.0
jobs:
  build:
    docker:
      - image: altosi/esp8266-sdk-build:0.0.1
    steps:
      - checkout
      - run:
          name: "Update submodules"
          command: |
            git submodule update --init --recursive
      - run:
          name: "Make"
          command: |
            CT_EXPERIMENTAL=y \
            CT_ALLOW_BUILD_AS_ROOT=y \
            CT_ALLOW_BUILD_AS_ROOT_SURE=y \
            make
      - run:
          name: "Compress Artifacts"
          command: |
            tar -czvf xtensa-lx106-elf.tar.gz xtensa-lx106-elf
      - store_artifacts:
          path: xtensa-lx106-elf.tar.gz
          destination: xtensa-lx106-elf.tar.gz
